# your domain
domain: kufei2020.herokuapp.com

# database url
database_url: "kufei2020.herokuapp.com"

# cloudflare api
cf_email: ""
cf_key: ""

# source definition file
source-files:
  # use local file
  - source.yaml
  # use web file
  - https://kufei2020.herokuapp.com/source.yaml
